// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// calib
Rcpp::List calib(arma::mat Y, arma::vec C, arma::mat Z, NumericVector mu_input, IntegerVector mu_dim, NumericVector mu0_input, IntegerVector mu0_dim, arma::mat S);
RcppExport SEXP MPG_calib(SEXP YSEXP, SEXP CSEXP, SEXP ZSEXP, SEXP mu_inputSEXP, SEXP mu_dimSEXP, SEXP mu0_inputSEXP, SEXP mu0_dimSEXP, SEXP SSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP );
        Rcpp::traits::input_parameter< arma::vec >::type C(CSEXP );
        Rcpp::traits::input_parameter< arma::mat >::type Z(ZSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type mu_input(mu_inputSEXP );
        Rcpp::traits::input_parameter< IntegerVector >::type mu_dim(mu_dimSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type mu0_input(mu0_inputSEXP );
        Rcpp::traits::input_parameter< IntegerVector >::type mu0_dim(mu0_dimSEXP );
        Rcpp::traits::input_parameter< arma::mat >::type S(SSEXP );
        Rcpp::List __result = calib(Y, C, Z, mu_input, mu_dim, mu0_input, mu0_dim, S);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// fit
Rcpp::List fit(arma::mat Y, arma::vec C, Rcpp::List prior, Rcpp::List mcmc, Rcpp::List state);
RcppExport SEXP MPG_fit(SEXP YSEXP, SEXP CSEXP, SEXP priorSEXP, SEXP mcmcSEXP, SEXP stateSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP );
        Rcpp::traits::input_parameter< arma::vec >::type C(CSEXP );
        Rcpp::traits::input_parameter< Rcpp::List >::type prior(priorSEXP );
        Rcpp::traits::input_parameter< Rcpp::List >::type mcmc(mcmcSEXP );
        Rcpp::traits::input_parameter< Rcpp::List >::type state(stateSEXP );
        Rcpp::List __result = fit(Y, C, prior, mcmc, state);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
