# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calib <- function(Y, C, Z, mu_input, mu_dim, mu0_input, mu0_dim, S) {
    .Call('MPG_calib', PACKAGE = 'MPG', Y, C, Z, mu_input, mu_dim, mu0_input, mu0_dim, S)
}

fit <- function(Y, C, prior, mcmc, state) {
    .Call('MPG_fit', PACKAGE = 'MPG', Y, C, prior, mcmc, state)
}

